[package]
name = "filetools"
version = "0.1.0"
authors = ["Graham Keenan <graham.keenan@outlook.com>"]
edition = "2018"
description = "Port of Jonathan Grizou's filetools Python library (https://github.com/jgrizou/filetools)"
repository = "https://github.com/Tyrannican/filetools-rs"
license = "MIT"
keywords = ["files", "utility", "filesystem"]
categories = ["filesystem"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.3"
uuid = { version = "0.8.1", features = ["v4"]}